#ASSIGNMENT 2
USE MYDB2;
#Q51
SELECT NAME, POPULATION ,AREA FROM COUNTRIES WHERE  POPULATION > 25000000 OR AREA > 3000000;

#Q52
SELECT NAME FROM CUSTOMER WHERE REFEREE_ID != 2
UNION
SELECT NAME FROM CUSTOMER WHERE referee_id IS NULL;

#Q53
SELECT DISTINCT NAME FROM CUSTOMERS WHERE ID NOT IN (SELECT CUSTOMERID FROM ORDERS);

#54
SELECT EMPLOYEE_ID, COUNT(TEAM_ID) OVER(PARTITION BY TEAM_ID) TEAM_SIZE FROM EMPLOYEE;

#55
use mydb2;
SELECT count(co.name)
FROM Person p
JOIN Country co
ON SUBSTRING(phone_number,1,3) = country_code
JOIN Calls c
ON p.id IN (c.caller_id, c.callee_id)
GROUP BY co.name
HAVING AVG(duration) > (SELECT AVG(duration) FROM Calls);

